### ISSUE TITLE
*** Error: Unhandled exception in the configuration script (most recent call last)   File "/opt/bess/bessctl/conf/up4.bess", line 138, in <module>     p.init_port(idx, parser.mode)   File "/opt/bess/bessctl/conf/ports.py", line 181, in init_port     raise Exception( Exception: Registered port for ens803f2 not detected!   Command failed: run up4

### ISSUE THREAD

**Issue by GIT-05112022** [omec-project/pfcpsim#64]
Every time i get this issue

**Comment by gab-arrobo** [comment]
@GIT-05112022, I do not understand why you get this error message in the `pfcpsim` because that error message is in the UPF and it looks like the UPF is not properly configured because it is trying to use some default configuration that points to port `ens803f2` and I am pretty sure you do not have that port/interface available in your system
