### ISSUE TITLE
Max Session Count

### ISSUE THREAD

**Issue by GIT-05112022** [omec-project/pfcpsim#67]
I just wonder, how many session does this tool makes at a given time.

**Comment by gab-arrobo** [comment]
It is defined as `int32` in [here](https://github.com/omec-project/pfcpsim/blob/main/internal/pfcpctl/commands/sessions.go#L83) and the number of sessions has to be `> 0` (due to [this check](https://github.com/omec-project/pfcpsim/blob/main/internal/pfcpctl/commands/sessions.go#L29)). So, up to 2147483647 and the number of sessions at a given time is given by `count` as shown in [here](https://github.com/omec-project/pfcpsim/blob/main/internal/pfcpctl/commands/sessions.go#L15)
